### ISSUE TITLE
답변 어제 확인해서 오늘 다시 질문드립니다 ..

### ISSUE THREAD

**Issue by DomaPark** [axboot/ax-boot-framework#11]
질문은 메이븐 에러방법을 못잡겠습니다..
도와주세요
참고로 저의 사양은 이렇습니다
JAVA : 1.8
OS : Windows 7 Home premium
STS : STS 3.8.2
![default](https://cloud.githubusercontent.com/assets/22976103/19842091/84961770-9f58-11e6-831d-05a641d6e29c.png)
![2](https://cloud.githubusercontent.com/assets/22976103/19842092/849e177c-9f58-11e6-8540-67e3117aee09.png)

즐거운 월요일 되세요 ..

**Comment by thomasJang** [comment]
https://api.axboot.com/install.html 이 문서를 보시면 start.axboot.com 이용하여 프로젝트 설치 하는 방법이 나와 있습니다. 
이걸 이용해서 셋팅 하시는 것이 더 좋을 것 같구요. 제가 알기론 다들 rombok 플러그인 설치가 안되서 문제가 있다고들 하던데요. 한번 확인 해보세요.

**Comment by DomaPark** [comment]
알겠습니다. 답변 감사합니다.
