### ISSUE TITLE
스키마 재생성오류

### ISSUE THREAD

**Issue by jsw418jj** [axboot/ax-boot-framework#12]
환경
이클립스 : Neon.1a Release (4.6.1)
java : jdk1.8.0_102
OS : winddow7 Professional k
was : apache-tomcat-7.0.72

소스를 변경한 부분은 없는데 갑자기 메뉴 클릭시 DB를 갔다오면서 오류가 발생합니다.
그래서 스키마 초기화를 하고 다시 하려고 setup페이지에서 초기화를 하니

ERROR com.chequer.axboot.core.controllers.BaseController:errorLogging:97 The database returned no natively generated identity value

이런 오류가 발생합니다.

어떻게 처리를 해야하나요??

**Comment by brant-hwang** [comment]
오라클의 경우는 AutoIncrement가 없기때문에 다음과 같이 시퀀스를 지정해주셔야 합니다.
```
@GeneratedValue(generator = "sequence")
@SequenceGenerator(name = "sequence", sequenceName = "SEQ_FILE_L", allocationSize = 1)
```
