### ISSUE TITLE
db 연동시 에러(오라클, mysql)

### ISSUE THREAD

**Issue by jsw418jj** [axboot/ax-boot-framework#16]
h2 db를 mysql로 변경해서 빌드후 로그인을 하고 나니 화면에 아무것도 나오지 않고 빈화면만 출력되고 eclipse console창에서는 메뉴 select query가 나오고 제일 하단에 null 이라고만 나와서 모가 문제 인지를 알수 가 없습니다. 

db를 변경해서 빌드만 하면 메인페이지가 아무것도 나오지를 않고 null이라고 만 나옵니다.

db 변경을 할때 axboot-local.properties 파일에서 db정보만 변경해 주면 되는것 아닌가여??
오라클에서도 mysql에서도 null 이 나오고 화면 출력이 안되고 있어서 문의드립니다.

그리고 mybatis를 연동해서  mapper를 사용하고 싶은데 설정을 어떻게 해야 하나요??

**Comment by brant-hwang** [comment]
MySQL 사용시에는 다음과 같이 프로퍼티를 설정하시면 됩니다.

axboot.dataSource.username={username}
axboot.dataSource.password={password}
axboot.dataSource.url=jdbc:mysql://{서버주소}/{데이터베이스명}
axboot.dataSource.driverClassName=com.mysql.jdbc.Driver
axboot.dataSource.initialSize=5
axboot.dataSource.maxIdle=-1
axboot.dataSource.maxTotal=10
axboot.dataSource.maxWaitMillis=3000
axboot.dataSource.slowQueryThreshold=3000
axboot.dataSource.hibernate.hbm2ddlAuto=none
axboot.dataSource.hibernate.databaseType=mysql
axboot.dataSource.hibernate.dialect=MySQL57InnoDBDialect

start.axboot.com에서 프로젝트 생성 후 axboot-loca.properties를 위 형태로 변경한 하고 테스트 해본결과 정상적으로 setup이 잘 진행됩니다.

Mybatis에 대한 설정은 추후 문서를 업데이트 하겠습니다.

**Comment by brant-hwang** [comment]
MyBatis 사용 가이드가 업데이트 되었습니다. https://api.axboot.com/back-end/mybatis.html

**Comment by jsw418jj** [comment]
답변 감사합니다.

개발상 오라클을 사용해야 하는데 이부분은 연동 테스트하면서 진행을 해야 겠네요.
잘 사용하겠습니다 

감사합니다.
