### ISSUE TITLE
system-auth-user.js 문의

### ISSUE THREAD

**Issue by jsw418jj** [axboot/ax-boot-framework#17]
system-auth-user.jsp  사용자 관리 페이지에서 비밀번호 변경 체크박스를 클릭하면 readonly부분이 풀려야 되는것 같은데 아무 액션도 일어나지 않습니다.

```
initEvent: function () {
        var _this = this;
        console.log(this.model); 
        $("input[name=password_change]").click(function(){
        	console.log(this.value);
        });
        
        this.model.onChange("password_change",function(){
        	console.log("asfadsf1");
    	});
        this.model.onClick("password_change",function(){
        	console.log("asfadsf2");
        });
//        this.model.onChange("password_change", function () {
//        	console.log("asfadsf"); 
//            if (this.value == "Y") {
//                _this.target.find('[data-ax-path="userPs"]').removeAttr("readonly");
//                _this.target.find('[data-ax-path="userPs_chk"]').removeAttr("readonly");
//            } else {
//                _this.target.find('[data-ax-path="userPs"]').attr("readonly", "readonly");
//                _this.target.find('[data-ax-path="userPs_chk"]').attr("readonly", "readonly");
//            }
//        });
    },
```
테스트를 해본다고 이것 저것을 다해봤는데 아무 반응이 없네요 
jquery 로 접근을 하면 console에 값이 찍히는것은 확인 했습니다.

**Comment by thomasJang** [comment]
<img width="1071" alt="capture" src="https://cloud.githubusercontent.com/assets/5884902/20045004/fe274f86-a4e0-11e6-971f-33b633be4866.png">

데모페이지를 확인 했을 때 재현이 되지 않습니다.
디버그를 위해선 에러가나는 브라우저 정보가 필요하구요.
지금 사용중인 JS들이 최신버전인지 확인이 필요합니다.

최신 소스를 다운로드 받으신 후 assets 폴더를 최신소스로 교체해보세요

**Comment by jsw418jj** [comment]
브라우저 정보 : 크롬 버전 54.0.2840.71 m (64-bit)
js가 최신인지는 어떻게 확인을 해야 하나요??
현재 소스는 AXBOOT INITIALIZR로 생성하여 만들어서 사용하고 있습니다.

최신소스를 다운로드 받으라고 하신 것은 AXBOOT INITIALIZR로 새로 소스를 생성하라는것 인가요??

**Comment by thomasJang** [comment]
https://github.com/axboot/ax-boot-framework/releases/tag/2.1.14 이걸 내려 받아서. 
`ax-boot-framework/ax-boot-admin/src/main/webapp/assets/`
를 확인 해보세용

**Comment by jsw418jj** [comment]
ax -boot-core 버젼은 2.1.10으로 사용하고 있었습니다.
답글을 늦게 봐서 axboot initailizr에서 새로 프로젝트를 다운받아 assets파일을 복사해서 넣어습니다. 

h2 db로 연동해서 빌드를 하고 확인 하니 문의 드렸던 내용은 잘나옵니다.

h2 db를 mysql로 변경해서 빌드후 로그인을 하고 나니 화면에 아무것도 나오지 않고 빈화면만 출력되고 eclipse console창에서는 메뉴 select query가 나오고 제일 하단에
null 이라고만 나와서 모가 문제 인지를 알수 가 없습니다. 

제가 이슈에도 문의를 했었는데 db를 변경해서 빌드만 하면 메인페이지가 아무것도 나오지를 않고 null이라고 만 나옵니다.

db 변경을 할때 axboot-local.properties 파일에서 db정보만 변경해 주면 되는것 아닌가여??
오라클에서도 mysql에서도 null 이나오고 화면 출력이 안되고 있어서 문의드립니다.

그리고 mybatis를 연동해서  mapper를 사용하고 싶은데 설정을 어떻게 해야 하나요??

**Comment by thomasJang** [comment]
👍  클라이언트 이슈가 해결 되셨으면 이 이슈는 닫아주시고 다음 이슈로 넘어가주세용~
