### ISSUE TITLE
CKEditor 사용법

### ISSUE THREAD

**Issue by jsw418jj** [axboot/ax-boot-framework#19]
CKEditorController가 있는데 에디터 사용이 가능한건가요??

가능하다면 설정을 어떻게 해야 하나요??

**Comment by brant-hwang** [comment]
Github 이슈는 개선 및 버그에 관련된 내용들을 올리는 공간입니다.

질문사항들은 다른 사용자들을 위해서 http://stackoverflow.com 에 남겨주세요.

감사합니다.

**Comment by jsw418jj** [comment]
죄송합니다.
알려주신곳으로 문의 드리겠습니다.
