### ISSUE TITLE
axtboot  init  를 다운로드 받았는데 컴파일 에러가 나서 확인 부탁드려요

### ISSUE THREAD

**Issue by peterkhang** [axboot/ax-boot-framework#25]
Qxxxxxx   로 시작하는 클래스를  소스트리에서 찾을 수가 없습니다.
설치가 잘못된 것인가요?

$mvn install
$npm install 
 로 패키지 설치는 했습니다.

확인 부탁드립니다.

package zoe.youngplussoft.antimalware.domain;

import zoe.youngplussoft.antimalware.domain.code.QCommonCode;
import zoe.youngplussoft.antimalware.domain.file.QCommonFile;
import zoe.youngplussoft.antimalware.domain.program.QProgram;
import zoe.youngplussoft.antimalware.domain.program.menu.QMenu;
import zoe.youngplussoft.antimalware.domain.user.QUser;
import zoe.youngplussoft.antimalware.domain.user.auth.QUserAuth;
import zoe.youngplussoft.antimalware.domain.user.auth.menu.QAuthGroupMenu;
import zoe.youngplussoft.antimalware.domain.user.role.QUserRole;
import com.chequer.axboot.core.domain.base.AXBootBaseService;
import com.chequer.axboot.core.domain.base.AXBootJPAQueryDSLRepository;

import java.io.Serializable;

public class BaseService<T, ID extends Serializable> extends AXBootBaseService<T, ID> {

    protected QUserRole qUserRole = QUserRole.userRole;
    protected QAuthGroupMenu qAuthGroupMenu = QAuthGroupMenu.authGroupMenu;
    protected QCommonCode qCommonCode = QCommonCode.commonCode;
    protected QUser qUser = QUser.user;
    protected QProgram qProgram = QProgram.program;
    protected QUserAuth qUserAuth = QUserAuth.userAuth;
    protected QMenu qMenu = QMenu.menu;
    protected QCommonFile qCommonFile = QCommonFile.commonFile;

    protected AXBootJPAQueryDSLRepository<T, ID> repository;

    public BaseService() {
        super();
    }

    public BaseService(AXBootJPAQueryDSLRepository<T, ID> repository) {
        super(repository);
        this.repository = repository;
    }
}

**Comment by brant-hwang** [comment]
http://stackoverflow.com/questions/40580093/axboot-baseservice-java-compile-error

Stackoverflow에 답변해드렸습니다 :)

**Comment by peterkhang** [comment]
감사합니다.

--------- 원본 메일 ---------

    
        보낸사람: Brant <notifications@github.com>
        받는사람: axboot/ax-boot-framework <ax-boot-framework@noreply.github.com>
        
            참조: peterkhang <mgkaki@daum.net>, Author <author@noreply.github.com>
        
        날짜: 2016년 11월 13일 일요일, 21시 06분 02초 +0900
        제목: Re: [axboot/ax-boot-framework] axtboot init 를 다운로드 받았는데 컴파일 에러가 나서 확인 부탁드려요 (#25)
        
        
    
    
        http://stackoverflow.com/questions/40580093/axboot-baseservice-java-compile-error

Stackoverflow에 답변해드렸습니다 :)
