### ISSUE TITLE
BaseService에서 몇몇 파일들을 찾을수가 없다고 나옵니다.

### ISSUE THREAD

**Issue by semanticker** [axboot/ax-boot-framework#28]
import com.chequer.axboot.admin.domain.code.QCommonCode;
import com.chequer.axboot.admin.domain.file.QCommonFile;
import com.chequer.axboot.admin.domain.program.QProgram;
import com.chequer.axboot.admin.domain.program.menu.QMenu;
import com.chequer.axboot.admin.domain.user.QUser;
import com.chequer.axboot.admin.domain.user.auth.QUserAuth;
import com.chequer.axboot.admin.domain.user.auth.menu.QAuthGroupMenu;
import com.chequer.axboot.admin.domain.user.role.QUserRole;

위 파일들을 찾을수 없어서 에러가 발생하고 있습니다.
예를 들면 com.chequer.axboot.admin.domain.code에는 QCommonCode 파일이 아니라 CommonCode 파일이 존재합니다.
제가 따로 설정해야 하는 부분이 있을까요?

**Comment by brant-hwang** [comment]
Stackoverflow 답변을 참고해주세요
http://stackoverflow.com/questions/40580093/axboot-baseservice-java-compile-error

**Comment by semanticker** [comment]
덕분에 잘 해결했습니다.
서버에 잘 올라가서 작동되네요.
고맙습니다.
