### ISSUE TITLE
메이븐 설정 오류 문제가있는데 해결방법좀 찾아주세요 ㅠㅠ

### ISSUE THREAD

**Issue by DomaPark** [axboot/ax-boot-framework#4]
설치하기 홈페이지에서 그대로 가져오는데 문제는 export하고 빌드를 할려고하는데
pom.xml에서 이런 오류가 뜹니다.
org.codehaus.gmavenplus:gmavenplus-plugin:1.5:add Sources (execution: default, phase: initialize)

이런에러가뜨는데 어떻게 해결하나요 ㅠㅠ
도와주세요~ ㅠㅠ

**Comment by brant-hwang** [comment]
구동하시는 환경, IDE, 스크린샷과 같은 더 자세한 정보가 필요합니다

**Comment by jsw418jj** [comment]
다른 분이 이슈에 추가 하신것 처럼 저도 설치하기로 해서 git으로 다운받아 설치를 했는데 
gmavenplus-plugin 1.5 에러가 발생합니다.

환경
이클립스 : Neon.1a Release (4.6.1)
java : 8

![1](https://cloud.githubusercontent.com/assets/23043263/19669598/a48e383a-9a9b-11e6-8fad-d3956b321165.jpg)

프로젝트 import 하고 난 후 에러 화면 입니다.

**Comment by jsw418jj** [comment]
자답입니다

gmavenplus 1.5 plugin 오류를 구글링을 통해 찾아보니 eGoveFrame 쪽에 비슷한 경우가 있어 처리 했습니다.
(참고 url : http://www.egovframe.go.kr/uss/olh/faq/FaqInqireCoUpdt.do?faqId=FAQ_0000000000000683&pageIndex=1)

위 url을 참고하여 오류를 처리 했습니다.

이클립스를 사용하는데 lombok .jar을 설치하지 않아 java쪽 에러가 발생하여 lombok을 설치하고 오류 해결했습니다.

**Comment by thomasJang** [comment]
👍  설치가이드에 lombox.jar 관련된 내용을 추가하겠습니다. 감사합니다.
