### ISSUE TITLE
tag 페이지 오류 

### ISSUE THREAD

**Issue by jsw418jj** [axboot/ax-boot-framework#7]
환경
이클립스 : Neon.1a Release (4.6.1)
java : jdk1.8.0_102
OS : winddow7 Professional k
was : apache-tomcat-7.0.72

위에 환경으로해서 설치를 하고 초기 스키마까지 생성해서 웹화면을 나오게 했습니다.
그런데 레프트메뉴에서 특정 페이지는 500에러가 발생합니다.

메뉴명
- 시스템관리
  - 메뉴관리
  - 사용자관리
  - 메뉴얼관리
- 레이아웃 샘플
  - 그리드&폼템플릿
  - 그리드&탭폼템플릿
  - 그리드&모달템플릿

위 메뉴들만 오류가 납니다.
에러로그

```
An error occurred at line: 23 in the jsp file: /WEB-INF/tags/common-code.tag
Cannot switch on a value of type String for source level below 1.7. Only convertible int values or enum variables are permitted
20: 
21:     List<CommonCode> commonCodes = CommonCodeUtils.get(groupCd);
22: 
23:     switch (type) {
24:         case "select":
25:             builder.append(String.format("<select id=\"%s\" name=\"%s\" data-ax-path=\"%s\" class=\"form-control %s\">", id, name, dataPath, clazz));
26: 
```

모든메뉴들 오류는 에러로그와 비슷합니다. 
구글링을 통해서 이클립스상에 java compile도 확인해봤는데 
현재 1.8로 되있습니다.

제가 설치를 하면서 잘못한거지 오류 확인 좀 부탁드립니다.

아 그리고 java buildpath를 jdk로 잡았다가 jre로 수정했습니다.

**Comment by brant-hwang** [comment]
Build Path에 Java Runtime은 JRE가 아니라 JDK를 사용하는것이 맞고요,
에러내용으로 보았을 때 이클립스에서 JDK 1.8 버전으로 정상 인식을 못하고 있는것 같습니다.

**Comment by jsw418jj** [comment]
혹시나 하고 1.7로 컴파일버젼을 변경해서 빌드를 해보니 1.8에서만 돌아가는 라이브러리 때문에 에러가
발생을 해서 다시 1.8로 컴파일을 하니 잘돌아 갑니다.

이클립스 버젼이 너무 최신인가해서 mars 버젼으로 새로 받아서도 해보고 
구버젼 jdk 때문인가해서 다 삭제하고도 해봤는데 계속 인식을 못하네요

우선 common-code.tag 파일의 switch 땨문에 나는 오류라 그부분을 int로 변경하는 코드를 넣어서 우선 돌아가게는 했습니다.

해결방법은 없는것인가요??

**Comment by brant-hwang** [comment]
common-code.tag파일에 있는 swtich 의 "" (String)  case 기능은 JDK 1.7 부터 추가된 기능이고요 (http://docs.oracle.com/javase/7/docs/technotes/guides/language/strings-switch.html) AX-Boot에서 특별히 제공하는 기능이 아닙니다. 즉, JSP 페이지에 컴파일 레벨이나, 컴파일 JDK 버전등을 추가로 확인해보셔야 할것같습니다. 아마도 Eclipse Language Level 설정이 1.7 이하로 되어있는게 아닌가 싶네요.
